import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

/** @type {import('tailwindcss').Config} */
export default {
  presets: [require("./blocks-plugin/tailwind-preset.cjs")],
  content: ["./index.html", "./src/**/*.{tsx,ts}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        muted: "var(--muted)",
        "beauty-taupe": "var(--primary)",
        "beauty-sand": "#C4A882",
      },
      fontFamily: {
        code: ["source-code-pro", "monospace"],
        ivyPresto: ["ivypresto-display", "serif"],
        ivyprestoHeadline: ["ivypresto-headline", "serif"],
        quasimoda: ["Quasimoda", "sans-serif"],
      },
      colors: {
        "bg-white": "#FEFDFC",
        "text-black01": "#060606",
        blue01: "#F3F4F8",
        blue02: "#D4DAE8",
        blue03: "#C4DEFF",
        blue60: "#EFF1F7",
        gray10: "#F1F1F1",
        gray20: "#E3E3E3",
        gray30: "#D5D5D5",
        gray50: "#F7F7F7",
        gray40: "#C7C7C7",
        gray60: "#ACACAC",
        gray80: "#909090",
        gray100: "#747474",
        gray400: "#ADADAD",
        pink10: "#FFF0F8",
        pink20: "#FFEAF5",
        pink30: "#FFDFEF",
        pink40: "#FFCAE5",
        pink60: "#FF87C4",
        pink100: "#DD1267",
        black: "#000000",
        white: "#ffffff",
        beige: "#FAF7F4",
        beige05: "#FEFDFC",
        green: "#6B9C7A",
        red: "#A54648",
        raspberry: "#DC1863",
        tomato: "#ff6347",
        "raspberry-light": "#FAECE6",
        "promo-bg": "#DD1267",
        "loyalty-pink": "#F3E5E0",
        "loyalty-blue": "#587ADA",
        "neon-yellow": "#f9fdbc",
        "border-gray": "#EDEDED",
        "text-secondary": "#7B7B7B",
      },
      fontSize: {
        10: "10px",
        11: "11px",
        22: "22px",
        13: "13px",
      },
    },
  },
  plugins: [],
};
